메인페이지
DSM-DanMuZi/dsm-danmuzi-frontend pull request #31
Opened 2023-03-13 10:04 UTC by hwangjinseong

## 작업 내용 설명

- [ ]  메인페이지
- [ ]  추천페이지 수정

## 주요 변경 사항

-  
- 

## 체크리스트

- [ ] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] 생성된 코드에 Javadoc 주석을 추가 하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈

- resolved #

2023-03-13 10:10 UTC, kimkh05 requested changes
파이팅 해봅시다..ㅎㅎ

2023-03-13 10:10 UTC, kimkh05 commented on package.json
> +    "react-router-dom": "^6.8.2",
react-router-dom 삭제 부탁드립니다. Next.js 라서 필요가 없네요

2023-03-13 10:10 UTC, kimkh05 commented on yarn.lock
> +"@remix-run/router@1.3.3":
아까 그거도 지우면 이거도 지워질거에요..ㅎㅎ

2023-03-14 05:32 UTC, kimkh05 requested changes
흠. 이거로 커밋수가 높은거구만요

2023-03-14 05:32 UTC, kimkh05 commented on components/advertisement/advertisement3.tsx
> +  background-color: ${({theme}) => theme.color.gray200};
Ctrl s

2023-03-14 05:32 UTC, kimkh05 commented on components/advertisement/numberbutton/index.tsx
>    maximumNum: string;
이걸 string 으로 받은 이유가 있나요?

2023-03-14 05:32 UTC, kimkh05 commented on components/advertisement/numberbutton/index.tsx
> +        setCount(count - 2);
여기부분도 maximum이 number type이면 더욱 알아보기 쉬울거 같은데

2023-03-14 05:32 UTC, kimkh05 commented on pages/main.tsx
> +      <NumberButton maximumNum="3" />
이거도 string 에서 number로.. 하하

2023-03-16 00:25 UTC, kimkh05 requested changes
아직 다 안끝난거 같아서..

2023-03-16 00:25 UTC, kimkh05 commented on pages/main.tsx
> +  -ms-overflow-style: none; /* 익스플로러, 앳지 */
주석 지워주세요. 싫음 말구

2023-03-16 08:08 UTC, kimkh05 requested changes

2023-03-16 08:08 UTC, kimkh05 commented on pages/main.tsx
> +  const components = [Advertisement1, Advertisement2, Advertisement3];
타입 지정좀 해주세요.

2023-03-16 08:08 UTC, kimkh05 commented on pages/main.tsx
> +    <MainWrapper className="scroll">
클래스 네임 추가한 이유가 있나요?

2023-03-16 08:08 UTC, kimkh05 commented on pages/main.tsx
> +        {components.map((Component, index) => (
여기 매핑할때도 타입 지정좀..

2023-03-16 08:08 UTC, kimkh05 commented on pages/main.tsx
> +            className={`component ${
이거는 스타일 컴포넌트 만든 뒤 props 넘기면서 해도 될거 같은데 그렇게 바꿔주실 수 있나요?

2023-03-16 09:57 UTC, hwangjinseong commented on pages/main.tsx
> +    <MainWrapper className="scroll">
아 없네요 ㅎㅎ

2023-03-17 02:17 UTC, hwangjinseong commented on pages/main.tsx
> +            className={`component ${
넵! 해볼게요

2023-03-17 06:27 UTC, yoon-ho7 approved these changes

2023-03-17 06:28 UTC, kimkh05 approved these changes

2023-03-17 06:28 UTC, kimkh05 commented on pages/main.tsx
> +type ComponentType = FC<{}>;
이거 한 이유가 있나요?

2023-03-17 06:28 UTC, kimkh05 commented on pages/main.tsx
> +type ComponentType = FC<{}>;
아 그거때문에

2023-03-17 06:28 UTC, kimkh05 commented
수고하셨습니다.

2023-03-17 10:10 UTC, merged